### ISSUE TITLE
void D2OReader::readIndexTable()

### ISSUE THREAD

**Issue by balciseri** [LuaxY/D2O-Reader#1]
Hello i'm not sure why but:
        `indexTable.insert(pair<int, int>(reader->ReadUInt(), reader->ReadUInt()));`
is populating the indexTable in a wrong way: the key is going in the second field and the pointer in the first so you can't use the table properly, 
Here a screen:http://puu.sh/nHfxP/53d989f4e4.png.
A possible fix could be: 

```
unsigned int key = reader->ReadUInt();
unsigned int pointer = reader->ReadUInt();
indexTable.insert(pair<int, int>(key, pointer));
```

In action: http://puu.sh/nHfDi/9496da7d7c.png

**Comment by LuaxY** [comment]
Hi !

Thanks for your suggestion, but this is very very old code totally unfinished. I have made python version of pack/unpack tools.

**Comment by balciseri** [comment]
Allright :smile:
